
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri May 25 14:45:36 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int CONST = 2;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 39;
  public static final int GREATER = 28;
  public static final int CONTINUE = 16;
  public static final int LESS = 30;
  public static final int RPAREN = 40;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 37;
  public static final int CLASS = 5;
  public static final int INC = 34;
  public static final int DIV = 24;
  public static final int ASSIGN = 45;
  public static final int IF = 7;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 26;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 3;
  public static final int MUL = 23;
  public static final int LESEQ = 31;
  public static final int ADD = 21;
  public static final int NUMBER = 19;
  public static final int MOD = 25;
  public static final int BREAK = 4;
  public static final int IDENT = 17;
  public static final int VOID = 12;
  public static final int LBRACE = 43;
  public static final int ELSE = 6;
  public static final int READ = 10;
  public static final int CHARCONST = 20;
  public static final int WHILE = 14;
  public static final int RBRACE = 44;
  public static final int BOOLCONST = 18;
  public static final int EXTENDS = 15;
  public static final int GREATEREQ = 29;
  public static final int DEC = 35;
  public static final int SEMICOMA = 36;
  public static final int SUB = 22;
  public static final int PRINT = 9;
  public static final int DO = 13;
}

